apiVersion: kni/v1alpha1

kind: KniHost
metadata:
  name: worker-0
spec:
  type: worker
  ipmi:
    address: 10.19.110.14
    credentialsName: ha-lab-ipmi-secret
  bootMACAddress: 00:73:49:3a:76:8e
  public_ipv4: 192.168.111.50


master_nodes = [
  {
    name: "${MASTER0_NAME}",
    public_ipv4: "${MASTER0_IP}",
    ipmi_host: "${MASTER0_IPMI_HOST}",
    ipmi_user: "${MASTER0_IPMI_USER}",
    ipmi_pass: "${MASTER0_IPMI_PASS}",
    mac_address: "${MASTER0_MAC}"
  }
]

bootstrap_public_ipv4 = "${BOOTSTRAP_IP}"
bootstrap_ipmi_host = "${BOOTSTRAP_IPMI_HOST}"
bootstrap_ipmi_user = "${BOOTSTRAP_IPMI_USER}"
bootstrap_ipmi_pass = "${BOOTSTRAP_IPMI_PASS}"

bootstrap_mac_address = "${BOOTSTRAP_MAC}"
nameserver= "$COREDNS_IP"

worker_nodes = [
  {
    name: "${WORKER0_NAME}",
    public_ipv4: "${WORKER0_IP}",
    ipmi_host: "${WORKER0_IPMI_HOST}",
    ipmi_user: "${WORKER0_IPMI_PASS}",
    mac_address: "${WORKER0_MAC}"
  }
]

worker_kernel = "assets/rhel_vmlinuz"
worker_initrd = "assets/rhel_initrd.img"
worker_kickstart = "http://${PROVISION_IP}:8080/assets/centos-rt-worker-kickstart.cfg"
