apiVersion: v1
baseDomain: tt.testing
compute:
 - name: worker
   replicas: 1
controlPlane:
   name: master
   platform: {}
   replicas: 1
metadata:
   name: test1
networking:
  clusterNetworks:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
   none: {}
pullSecret: 'garbage'
sshKey: |
   garbage