apiVersion: kni/v1alpha1

kind: KniHost
metadata:
  name: master-0
spec:
  online: false
  nodeType: master
  ipmi:
    address: 10.19.110.16
    credentialsName: ha-lab-ipmi-secret
  bootMACAddress: 0c:c4:7a:8e:ee:0c
  publicIPv4: 192.168.111.11

