apiVersion: metalkube.org/v1alpha1

kind: BareMetalHost
metadata:
  name: master-0
  annotations:
      kni.io/sdnNetworkMac: "0c:c4:7a:8e:ee:0c"
      foot: ball
spec:
  externallyProvisioned: true
  online: true
  hardwareProfile: "master"
  bmc:
    address: ipmi://10.19.110.16
    credentialsName: ha-lab-ipmi-secret
  bootMACAddress: 0c:c4:7a:8e:ee:0c


