apiVersion: kni/v1alpha1

kind: KniHost
metadata:
  name: worker-0
  annotations:
    kni.io/kernel: "assets/rhel_vmlinuz"
    kni.io/initrd: "assets/rhel_initrd.img"
    kni.io/kickstart: "http://${PROVISION_IP}:8080/assets/centos-rt-worker-kickstart.cfg"

spec:
  externallyProvisioned: true
  online: true
  hardwareProfile: "worker"
  bmc:
    address: ipmi://10.19.110.14
    credentialsName: ha-lab-ipmi-secret
  bootMACAddress: 0c:c4:7a:8e:ec:e8
  publicIPv4: 192.168.111.51

