apiVersion: metalkube.org/v1alpha1

kind: BareMetalHost
metadata:
  name: worker-0
  annotations:
    kni.io/sdnNetworkMac: "0c:c4:7a:8e:ed:c8"
    kni.io/kernel: "assets/rhel_vmlinuz"
    kni.io/initrd: "assets/rhel_initrd.img"
    kni.io/kickstart: "http://${PROVISION_IP}:8080/assets/centos-rt-worker-kickstart.cfg"

spec:
  externallyProvisioned: true
  online: true
  hardwareProfile: "worker"
  bmc:
    address: ipmi://10.19.110.18
    credentialsName: ha-lab-ipmi-secret
  bootMACAddress: 0c:c4:7a:8e:ed:c8

